### ISSUE TITLE
Use Downshift hooks

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [infoderm/patients#149]
- [x] `imports/ui/input/SearchBoxWithSuggestions.tsx` 43ef681
  - [x] `imports/ui/input/SetPicker.tsx` b5d95f0

See [the `useSelect` docs](https://www.downshift-js.com/use-select).

**Comment by aureooms** [comment]
Upgrading is not needed because we have downshift@^6.0.5 since c1624da66ca9d6cfc13d3e06c3adabef96d87e67.

**Comment by aureooms** [comment]
First attempt at writing a Combobox using `useCombobox` from `downshift` was not so successful. See branch https://github.com/infoderm/patients/tree/feature-combobox and #159.

**Comment by aureooms** [comment]
Maybe use `Autocomplete` and `useAutocomplete` from Material-UI instead?

**Comment by aureooms** [comment]
This worked very well for `AutocompleteWithSuggestions` in `TagRenamingDialog`. See #159.

**Comment by aureooms** [comment]
For `SetPicker` perhaps take inspiration from https://codesandbox.io/s/github/kentcdodds/downshift-examples?file=/src/downshift/ordered-examples/05-multi-create.js. Although it should be noted that `useDeepCompareEffect` is frowned upon.
