### ISSUE TITLE
Remove gridfs-stream dependency

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [infoderm/patients#157]
The last release of dependency [gridfs-stream](https://www.npmjs.com/package/gridfs-stream) was six years ago!
[Meteor-Files (ostrio:files)](https://github.com/VeliovGroup/Meteor-Files) can now be used without `gridfs-stream` as shown [in this GridFS demo](https://github.com/veliovgroup/files-gridfs-autoform-example).
Related to #33.

**Comment by aureooms** [comment]
The [docs](https://github.com/VeliovGroup/Meteor-Files/blob/master/docs/gridfs-bucket-integration.md#use-gridfs-with-gridfsbucket-as-a-storage).

**Comment by aureooms** [comment]
Not a bug. #33 was caused by something else. Moreover a dependency upgrade is not needed to do the move.

**Comment by make-github-pseudonymous-again** [comment]
Plus [`gridfs-stream` relies on deprecated `GridStore`](https://github.com/aheckmann/gridfs-stream/issues/135). See API docs [here](https://mongodb.github.io/node-mongodb-native/3.6/api/GridStore.html).

**Comment by make-github-pseudonymous-again** [comment]
Note that `gridfs-stream` was using `fs` has the default name for bucket. Either via [`GridStore`](https://mongodb.github.io/node-mongodb-native/3.6/api/GridStore.html#.DEFAULT_ROOT_COLLECTION) or [as a constant](https://github.com/aheckmann/gridfs-stream/blob/c394e050d066a5c81c6dcdddad186b08a93d5f1f/lib/index.js#L31). Because of that, current deployment uses `fs` as bucket name. The [new `GridFSBucket` API uses the same default](https://mongodb.github.io/node-mongodb-native/3.6/api/GridFSBucket.html). However, moving forward it is probably best to explicitly set this in our files.

**Comment by make-github-pseudonymous-again** [comment]
Note: In addition to all the remarks above, I use the guide at https://github.com/veliovgroup/Meteor-Files/blob/6a192b74537c705069ad60b21959ef2233b9f58b/docs/gridfs-bucket-integration.md
