### ISSUE TITLE
Patient attachments do not load unless patient consultations are preloaded

### ISSUE THREAD

**Issue by aureooms** [infoderm/patients#166]
Can't find the cause but I believe it used to work seamlessly before.

**Comment by aureooms** [comment]
See:
  - https://github.com/meteor/react-packages/pull/306
  - https://github.com/meteor/react-packages/pull/314

**Comment by CaptainN** [comment]
I have received at least one confirmation that the PR you referenced above fixes this, but would love some more validation. Can you test that?

**Comment by CaptainN** [comment]
Version 2.2.2 is out. Should fix this up.

**Comment by aureooms** [comment]
Thanks @CaptainN ! I will try it out as soon as I can.
