### ISSUE TITLE
Use async/await for Meteor method calls on client

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [infoderm/patients#184]
[This forum post](https://forums.meteor.com/t/async-callback-from-meteor-methods/43921/2?u=aureooms) suggests the following approach:

```js
const promisify = (f) => (...args) => new Promise((resolve, reject) =>
    f(...args, (error, result) => {
      if (error) reject(error);
      else resolve(result);
    })
);
const call = promisify(Meteor.call.bind(Meteor));
const apply = promisify(Meteor.apply.bind(Meteor));
  
try {
  const result = await apply(method, args, options);
  // or const result = await call(method, ...args);
  // ...
}
catch (error) {
  console.error(error);
}
```

```sh
rg 'Meteor\.call' imports/ server/ client/ -l | sort
```
  - [x] `imports/client/insertDocument.js`
  - [x] `imports/client/insertDrugs.js`
  - [x] `imports/client/insertPatient.js`
  - [x] `imports/client/settings.js`
  - [x] `imports/ui/allergies/AllergyCard.js` 66f214c
  - [x] `imports/ui/appointments/AppointmentCancellationDialog.js` 41cebf3
  - [x] `imports/ui/appointments/AppointmentDeletionDialog.js`
  - [x] `imports/ui/appointments/AppointmentUncancellationDialog.js`
  - [x] `imports/ui/appointments/EditAppointmentDialog.js`
  - [x] `imports/ui/appointments/NewAppointmentDialog.js`
  - [x] `imports/ui/attachments/AttachFileButton.js`
  - [x] `imports/ui/attachments/AttachmentDeletionDialog.js`
  - [x] `imports/ui/attachments/AttachmentEditionDialog.js`
  - [x] `imports/ui/attachments/AttachmentLinkingDialog.js`
  - [x] `imports/ui/books/BooksDownloadDialog.js` 2be72c6
  - [x] `imports/ui/consultations/ConsultationAppointmentRestorationDialog.js`
  - [x] `imports/ui/consultations/ConsultationDebtSettlementDialog.js`
  - [x] `imports/ui/consultations/ConsultationDeletionDialog.js`
  - [x] `imports/ui/consultations/ConsultationForm.js` 4841a4cbcea4875835756072436e38db34114f49
  - [x] `imports/ui/consultations/StaticConsultationCardActions.js`
  - [x] `imports/ui/documents/DocumentDeletionDialog.js`
  - [x] `imports/ui/documents/DocumentLinkingDialog.js`
  - [x] `imports/ui/documents/DocumentRestorationDialog.js`
  - [x] `imports/ui/documents/DocumentSuperDeletionDialog.js`
  - [x] `imports/ui/documents/DocumentUnlinkingDialog.js`
  - [x] `imports/ui/drugs/DrugsTable.js`
  - [x] `imports/ui/merge/MergePatientsConfirmationDialog.js`
  - [x] `imports/ui/patients/NewPatientForm.js` a7b7bfc
  - [x] `imports/ui/patients/PatientDeletionDialog.js`
  - [x] `imports/ui/patients/PatientPersonalInformationStatic.js`
  - [x] `imports/ui/patients/PatientsSearchResults.js`
  - [x] `imports/ui/tags/TagDeletionDialog.js`
  - [x] `imports/ui/tags/TagRenamingDialog.js`

**Comment by aureooms** [comment]
- [ ] `imports/client/insertDocument.js`
  - [ ] `imports/client/insertDrugs.js`
  - [ ] `imports/client/insertPatient.js`
  - [ ] `imports/client/settings.js`
  - [ ] `imports/ui/allergies/AllergyCard.js`
  - [ ] `imports/ui/appointments/AppointmentCancellationDialog.js`
  - [ ] `imports/ui/appointments/AppointmentDeletionDialog.js`
  - [ ] `imports/ui/appointments/AppointmentUncancellationDialog.js`
  - [ ] `imports/ui/appointments/EditAppointmentDialog.js`
  - [ ] `imports/ui/appointments/NewAppointmentDialog.js`
  - [ ] `imports/ui/attachments/AttachFileButton.js`
  - [ ] `imports/ui/attachments/AttachmentDeletionDialog.js`
  - [ ] `imports/ui/attachments/AttachmentEditionDialog.js`
  - [ ] `imports/ui/attachments/AttachmentLinkingDialog.js`
  - [ ] `imports/ui/books/BooksDownloadDialog.js`
  - [ ] `imports/ui/consultations/ConsultationAppointmentRestorationDialog.js`
  - [ ] `imports/ui/consultations/ConsultationDebtSettlementDialog.js`
  - [ ] `imports/ui/consultations/ConsultationDeletionDialog.js`
  - [ ] `imports/ui/consultations/ConsultationForm.js`
  - [ ] `imports/ui/consultations/StaticConsultationCardActions.js`
  - [ ] `imports/ui/documents/DocumentDeletionDialog.js`
  - [ ] `imports/ui/documents/DocumentLinkingDialog.js`
  - [ ] `imports/ui/documents/DocumentRestorationDialog.js`
  - [ ] `imports/ui/documents/DocumentSuperDeletionDialog.js`
  - [ ] `imports/ui/documents/DocumentUnlinkingDialog.js`
  - [ ] `imports/ui/drugs/DrugsTable.js`
  - [ ] `imports/ui/merge/MergePatientsConfirmationDialog.js`
  - [ ] `imports/ui/patients/NewPatientForm.js`
  - [ ] `imports/ui/patients/PatientDeletionDialog.js`
  - [ ] `imports/ui/patients/PatientPersonalInformationStatic.js`
  - [ ] `imports/ui/patients/PatientsSearchResults.js`
  - [ ] `imports/ui/tags/TagDeletionDialog.js`
  - [ ] `imports/ui/tags/TagRenamingDialog.js`

**Comment by make-github-pseudonymous-again** [comment]
Waiting on #170.
