### ISSUE TITLE
Material-UI: Replace rightIcon/leftIcon by native endIcon/startIcon

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [infoderm/patients#198]
```sh
rg '(leftIcon|rightIcon)' imports/ server/ client/ -l | sort
```

  - [x] `imports/ui/ErrorPage.js` 917ef31
  - [ ] `imports/ui/appointments/AppointmentDialog.js`
  - [ ] `imports/ui/appointments/AppointmentDeletionDialog.js`
  - [ ] `imports/ui/tags/TagRenamingDialog.js`
  - [x] `imports/ui/tags/TagDeletionDialog.js` 1955b03009f5bac1c4651eb27ae9fd884bb41e7e
  - [x] `imports/ui/users/Dashboard.js` cba79231
  - [x] `imports/ui/users/SignInForm.js` 686af48
  - [ ] `imports/ui/appointments/AppointmentUncancellationDialog.js`
  - [x] `imports/ui/appointments/AppointmentCancellationDialog.js` 41cebf3
  - [ ] `imports/ui/patients/MissingPatientCard.js`
  - [ ] `imports/ui/patients/PatientDeletionDialog.js`
  - [x] `imports/ui/patients/PatientRecord.js` de127a4
  - [x] `imports/ui/modal/ConfirmationDialog.js` 3528235
  - [x] `imports/ui/patients/NewPatientCard.js` abe14bffad599067f9e6820e7784451672237dba
  - [ ] `imports/ui/merge/MergePatientsConfirmationDialog.js`
  - [x] `imports/ui/merge/MergePatientsFormStepPrepare.js` 60e23179d408aa4882462aecf17d6d2f4f1d53f6
  - [ ] `imports/ui/documents/DocumentDeletionDialog.js`
  - [ ] `imports/ui/documents/DocumentSuperDeletionDialog.js`
  - [x] `imports/ui/documents/DocumentLinkingDialog.js` 075cd56
  - [x] `imports/ui/merge/MergePatientsForm.js` e2469f84b4f7e938745ee566b19e232b44fbdeeb
  - [ ] `imports/ui/consultations/ConsultationDeletionDialog.js`
  - [ ] `imports/ui/consultations/ConsultationPaymentDialog.js`
  - [x] `imports/ui/documents/DocumentUnlinkingDialog.js` 075cd56
  - [x] `imports/ui/consultations/ConsultationDebtSettlementDialog.js` 701b666
  - [ ] `imports/ui/consultations/ConsultationAppointmentRestorationDialog.js`
  - [ ] `imports/ui/consultations/ConsultationsForPatientStatic.js`
  - [ ] `imports/ui/attachments/AttachmentDeletionDialog.js`
  - [x] `imports/ui/attachments/AttachmentLinkingDialog.js` 5956bd8
  - [x] `imports/ui/books/BooksDownloadDialog.js` cdacb62b8f77805d4d2524b0cd4d7486275e7601
  - [ ] `imports/ui/attachments/AttachmentEditionDialog.js`
  - [ ] `imports/ui/attachments/AttachmentSuperDeletionDialog.js`
  - [ ] `imports/ui/documents/DocumentRestorationDialog.js`

**Comment by aureooms** [comment]
- [ ] `imports/ui/ErrorPage.js`
  - [ ] `imports/ui/appointments/AppointmentDialog.js`
  - [ ] `imports/ui/appointments/AppointmentDeletionDialog.js`
  - [ ] `imports/ui/tags/TagRenamingDialog.js`
  - [ ] `imports/ui/tags/TagDeletionDialog.js`
  - [ ] `imports/ui/users/Dashboard.js`
  - [ ] `imports/ui/users/SignInForm.js`
  - [ ] `imports/ui/appointments/AppointmentUncancellationDialog.js`
  - [ ] `imports/ui/appointments/AppointmentCancellationDialog.js`
  - [ ] `imports/ui/patients/MissingPatientCard.js`
  - [ ] `imports/ui/patients/PatientDeletionDialog.js`
  - [ ] `imports/ui/patients/PatientRecord.js`
  - [ ] `imports/ui/modal/ConfirmationDialog.js`
  - [ ] `imports/ui/patients/NewPatientCard.js`
  - [ ] `imports/ui/merge/MergePatientsConfirmationDialog.js`
  - [ ] `imports/ui/merge/MergePatientsFormStepPrepare.js`
  - [ ] `imports/ui/documents/DocumentDeletionDialog.js`
  - [ ] `imports/ui/documents/DocumentSuperDeletionDialog.js`
  - [ ] `imports/ui/documents/DocumentLinkingDialog.js`
  - [ ] `imports/ui/merge/MergePatientsForm.js`
  - [ ] `imports/ui/consultations/ConsultationDeletionDialog.js`
  - [ ] `imports/ui/consultations/ConsultationPaymentDialog.js`
  - [ ] `imports/ui/documents/DocumentUnlinkingDialog.js`
  - [ ] `imports/ui/consultations/ConsultationDebtSettlementDialog.js`
  - [ ] `imports/ui/consultations/ConsultationAppointmentRestorationDialog.js`
  - [ ] `imports/ui/consultations/ConsultationsForPatientStatic.js`
  - [ ] `imports/ui/attachments/AttachmentDeletionDialog.js`
  - [ ] `imports/ui/attachments/AttachmentLinkingDialog.js`
  - [ ] `imports/ui/books/BooksDownloadDialog.js`
  - [ ] `imports/ui/attachments/AttachmentEditionDialog.js`
  - [ ] `imports/ui/attachments/AttachmentSuperDeletionDialog.js`
  - [ ] `imports/ui/documents/DocumentRestorationDialog.js`
