### ISSUE TITLE
Do not reset state when switching from Weekly to Monthly planner and vice versa

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [infoderm/patients#199]

**Comment by aureooms** [comment]
Partial progress in 27c3d7a

**Comment by make-github-pseudonymous-again** [comment]
I can see two options so far: [`react-redux`](https://react-redux.js.org/) or [`React.createContext`](https://reactjs.org/docs/context.html).

**Comment by make-github-pseudonymous-again** [comment]
I think the explanation as to why the reset happens lies in [React's reconciliation logic](https://reactjs.org/docs/reconciliation.html#elements-of-different-types) which skips reconciliation attempt of nodes having different types. No idea if there is a way around it. We would just need a way to hint that at the next level some of the children nodes are of the same type as the children nodes of the replaced root.
