### ISSUE TITLE
Unable to resolve module "canvas"

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [infoderm/patients#227]
Getting this error with `npm run dev`
```
Unable to resolve some modules:

  "canvas" in /home/aureooms/dev/dermatodoc/patients/node_modules/pdfjs-dist/build/pdf.js (web.browser.legacy)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save canvas       
```

**Comment by aureooms** [comment]
Ok digging a bit it seems that [`pdfjs-dist` requires a bunch of external modules](https://github.com/mozilla/pdfjs-dist/blob/75158b4de095a6ce6c13fe165f98810ca9e63be6/package.json#L18-L25), but only when running in Node. Not a problem as long as I use the library in the browser exclusively. If you want to call it from Node I guess you would have to install all these dependencies.
