### ISSUE TITLE
Suggest patients to merge with when inserting ID card info

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [infoderm/patients#231]
Handle misspellings etc

**Comment by aureooms** [comment]
When there is no NN exact match suggest patients with similar names. Perhaps with a search box prefilled with the name on the ID card.

**Comment by make-github-pseudonymous-again** [comment]
This has been implemented while keeping in mind that perhaps a merge functionality will be implemented later. Currently the user can only select a single record to update. The system can already handle multiple selection input, all that is left to do is to implement what to do in case of such a selection. This will be for another issue if raised after discussion.
