### ISSUE TITLE
Upgrade mup deploy config to use mongo 4.4.

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [infoderm/patients#246]
I'll probably go with a backup/restore approach to do the migration.

**Comment by aureooms** [comment]
Another way, given current version is 3.6 is to first [upgrade to 4.0](https://docs.mongodb.com/manual/release-notes/4.0-upgrade-standalone/) then [upgrade to 4.2](https://docs.mongodb.com/manual/release-notes/4.2-upgrade-standalone/), and finally [upgrade to 4.4](https://docs.mongodb.com/manual/release-notes/4.4-upgrade-standalone/).
