### ISSUE TITLE
Improve doneDatetime update logic

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [infoderm/patients#250]
Only one button and guess. Only update if edit time is close enough to last edit time (~2 hours is safe). Otherwise allow to override manually (in header?).

**Comment by aureooms** [comment]
Instead of ~2 hours use duration if available?

**Comment by make-github-pseudonymous-again** [comment]
Could also check if this consultation is the last consultation. This assumes no consultation parallelism.

**Comment by make-github-pseudonymous-again** [comment]
Manual override missing in be94c4b. Might implement later if needed.

**Comment by make-github-pseudonymous-again** [comment]
With fae8add doneDatetime is displayed in the header.
