### ISSUE TITLE
Cache attachment thumbnails

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [infoderm/patients#93]
Using [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)? Or some abstraction on top of it.

**Comment by aureooms** [comment]
For instance [storage-lru](https://github.com/YahooArchive/storage-lru) but archived :(.

**Comment by aureooms** [comment]
Could also generate and cache the thumbnail on the server using a specific route??

**Comment by aureooms** [comment]
Now that we have a `useThumbnail` hook it should be easy to implement LRU caching in the browser.

**Comment by aureooms** [comment]
This looks much more complicated than originally planned. For the following reasons:
  - [`Cache`](https://developer.mozilla.org/en-US/docs/Web/API/Cache) and [`IndexedDB`](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) do not provide automated garbage collection (LRU or other) ([although this seems to be a contradiction](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#lru_policy) unless this statement is about the browser unmanaged resource cache).
  - [`LocalStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) does not provide indices and is rather limited in storage space.
  - [`localForage`](https://localforage.github.io/localForage) alone does not provide garbage collection (and weights 8KB).
  - There is [`localforage-lru-driver`](https://github.com/liqwid/localforage-lru-driver) but last release 4 years ago and [I doubt it would perform well in extreme situations](https://github.com/liqwid/localforage-lru-driver/issues/5).
  - [`localforage-indexes`](https://github.com/liqwid/localforage-indexes) gives access to `IndexedDB` indices through `localforage`, but again, old package.
  - [`Dexie`](https://github.com/dfahlander/Dexie.js) is 22KB, [`PouchDB`](https://pouchdb.com/) is 37KB.
  - Another solution is to persist any of the existing "lru-cache" NPM implementations. But:
    - We hit the same storage space limits as the underlying persit solution.
    - I cannot find any implementation that supports custom eviction logic (especially storage quota), they are all based on entry count.

**Conclusion**: it looks more manageable and less bloated to just implement everything from scratch with `IndexedDB`. I must admit it also looks like a tempting experiment. Unfortunately, at the moment, I cannot find a way to obtain storage usage for a specific database or store (table). There is [`StorageEstimate`](https://developer.mozilla.org/en-US/docs/Web/API/StorageEstimate) accessed through [`navigator.storage.estimate()`](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate) but it only gives a partition by type of storage. Plus at the moment it seems firefox fails to yield [`usageDetails`](https://developer.mozilla.org/en-US/docs/Web/API/StorageEstimate#properties).

**Comment by aureooms** [comment]
**PS**: [`idb`](https://github.com/jakearchibald/idb) looks great to get an `async/await` API on top of `IndexedDB`.

**Comment by aureooms** [comment]
See branch https://github.com/infoderm/patients/tree/feature-cache-thumbnails

**Comment by make-github-pseudonymous-again** [comment]
See also https://jlongster.com/future-sql-web
